### ISSUE TITLE
Error al login

### ISSUE THREAD

**Issue by cguillencr** [UCR-Paraiso-Lenguajes/lenguajes24#343]
Los usuarios no se pueden logear

Steps

1. Ingrese a http://localhost:3000/Admin
2. Use Diego/secret

Resultado Actual
![image](https://github.com/UCR-Paraiso-Lenguajes/lenguajes24/assets/3529048/2af709bf-0ff2-4f15-8857-ce480fb1e892)

Resultado Esperado
El login debe funcionar bien

**Comment by EisenheimDiego** [comment]
El error era que no se estaba desplegando un erro de forma correcta. 

- **Se cambió el despliegue del error**
