### ISSUE TITLE
Errores al crear productos

### ISSUE THREAD

**Issue by cguillencr** [UCR-Paraiso-Lenguajes/lenguajes24#365]
En la pagina de crear productos 

1. No permite crear productos con urls válidas.
2. El campo de autor debe llamarse descripción y ser un text area. INcluyendo variables de ambientey campos en la bd
3. Este campo debe ser un blod

**Comment by Lani6** [comment]
De url validas va incluido que puede ingresar un video de youtube? o eso era para description?
